version: '3.9'

services:

  db:
    image: postgres:alpine
    container_name: "api_db"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=api
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

  app:
    build: .
    container_name: "api-server"
    command: sh -c "npm start"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db
    environment:
      - VITE_API=
      - PGHOST=db
      - PGDATABASE=api
      - PGUSER=postgres
      - PGPASSWORD=root
